site_name: Mkdocs example
site_description: Mkdocs example project
site_author: manboubird

repo_url: https://github.com/manboubird/doc-as-code-example
repo_name: doc-as-code-example

docs_dir: docs
theme: readthedocs
extra_css: [_static/css/extra.css]

extra:
    version: 1

pages:
    - Home: index.md
    - Project:
        - Release Notes: project/release-notes.md

